kind: Service
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-svc
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
    {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
spec:
  {{- if .Values.service.loadBalancer }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
  selector:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
  ports:
    - name: service
      port: 9000
      targetPort: 9000
      protocol: TCP
