apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-creds
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
type: Opaque
data:
  accesskey: {{ .Values.creds.accessKey | b64enc }}
  secretkey: {{ .Values.creds.secretKey | b64enc }}
