apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
  ports:
    - name: rest
      port: {{ .Values.restPort }}
      targetPort: {{ .Values.restPort }}
    - name: transport
      port: {{ .Values.transportPort }}
      targetPort: {{ .Values.transportPort }}
