apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-elasticsearch
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: elasticsearch
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    application: {{ template "fullname" . }}
    component: elasticsearch
  ports:
    - name: es-rest
      port: {{ .Values.elasticsearch.restPort }}
      targetPort: {{ .Values.elasticsearch.restPort }}
    - name: es-transport
      port: {{ .Values.elasticsearch.transportPort }}
      targetPort: {{ .Values.elasticsearch.transportPort }}
