apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-elasticsearch-api
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: elasticsearch
    es-role: client
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- if .Values.elasticsearch.service.annotations }}
{{ toYaml .Values.elasticsearch.service.annotations | indent 4 }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.port }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    application: {{ template "fullname" . }}
    component: elasticsearch
    es-role: client
  ports:
    - name: rest
      port: {{ .Values.elasticsearch.restPort }}
      targetPort: {{ .Values.elasticsearch.restPort }}
