apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: kibana
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  {{- if .Values.kibana.service.loadBalancer }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
  selector:
    application: {{ template "fullname" . }}
    component: kibana
  ports:
    - name: kibana-port
      port: {{ .Values.kibana.port }}
      targetPort: {{ .Values.kibana.port }}
