apiVersion: v1
kind: Secret
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- if .Values.logstash.service.annotations }}
{{ toYaml .Values.logstash.service.annotations | indent 4 }}
    {{- end }}
  name: {{ template "fullname" . }}-logstash-certs
  labels:
    application: {{ template "fullname" . }}
    component: logstash
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  logstash.crt: {{ .Values.logstash.ssl.cert }}
  logstash.key: {{ .Values.logstash.ssl.key }}
