apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-logstash-config
  labels:
    application: {{ template "fullname" . }}
    component: logstash
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  {{- if .Values.logstash.lumberjack.enabled }}
  01-lumberjack-input.conf: |-
    input {
      lumberjack {
        port            => {{ .Values.logstash.lumberjack.port }}
        ssl_certificate => "/etc/ssl/logstash/logstash.crt"
        ssl_key         => "/etc/ssl/logstash/logstash.key"
        tags            => ["logstash-forwarder"]
      }
    }
  {{- end }}
  {{- if .Values.logstash.beats.enabled }}
  02-beats-input.conf: |-
    input {
      beats {
        port            => {{ .Values.logstash.beats.port }}
        ssl             => true
        ssl_certificate => "/etc/ssl/logstash/logstash.crt"
        ssl_key         => "/etc/ssl/logstash/logstash.key"
      }
    }
  {{- end }}
  {{- if .Values.logstash.syslog.enabled }}
  03-syslog-input.conf: |-
    input {
      syslog {
        facility_labels => [
          'KERNEL'  ,
          'USER'    ,
          'MAIL'    ,
          'DAEMON'  ,
          'AUTH'    ,
          'SYSLOG'  ,
          'LPR'     ,
          'NEWS'    ,
          'UUCP'    ,
          'CRON'    ,
          'AUTHPRIV',
          'FTP'     ,
          'NTP'     ,
          'AUDIT'   ,
          'CONSOLE' ,
          'CRON'    ,
          'LOCAL0'  ,
          'LOCAL1'  ,
          'LOCAL2'  ,
          'LOCAL3'  ,
          'LOCAL4'  ,
          'LOCAL5'  ,
          'LOCAL6'  ,
          'LOCAL7'
        ]
        tags => ['syslog']
      }
    }
  {{- end }}
  30-elasticsearch-output.conf: |-
    output {
      if ![error] and [_type] {
        elasticsearch {
          protocol        => "transport"
          hosts           => ["{{ template "fullname" . }}-elasticsearch-api.{{ .Release.Namespace }}.svc.cluster.local:9200"]
          cluster         => "{{ .Values.clusterName }}"
          sniffing        => true
          manage_template => false
          document_type   => "%{_type}"
        }
      }
    }
  31-error-stdout.conf: |-
    output {
      if [error] {
        stdout {
          codec => rubydebug
        }
      }
    }
  {{- if .Values.logstash.filters }}
    {{- range $key, $value := .Values.logstash.filters }}
  {{ $key }}: |-
{{ $value | indent 4 }}
    {{- end }}
  {{- end }}
