apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-logstash-certs
  labels:
    application: {{ template "fullname" . }}
    component: logstash
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  logstash.crt: {{ .Values.logstash.ssl.cert }}
  logstash.key: {{ .Values.logstash.ssl.key }}
