apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}-elasticsearch-sa
  labels:
    application: {{ template "fullname" . }}
    component: elasticsearch
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
