{{- if .Values.rockmongo.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-rockmongo
  labels:
    application: {{ template "fullname" . }}
    component: rockmongo
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.php: |-
    <?php
    /**
     * RockMongo configuration
     *
     * Defining default options and server configuration
     * @package rockmongo
     */
    $MONGO = array();
    $MONGO["features"]["log_query"] = "on";//log queries
    $MONGO["features"]["theme"] = "default";//theme
    $MONGO["features"]["plugins"] = "on";//plugins

    $seeds = array();
    $mongo_hosts = explode(",", getenv("MONGO_HOSTS"));
    for ($i = 0; $i < count($mongo_hosts); $i++) {
        $host_port = explode(":", $mongo_hosts[$i]);

        $seeds[$i]["name"] = explode(".", $host_port[0])[0];
        $seeds[$i]["host"] = $host_port[0];
        $seeds[$i]["port"] = 27017;
        if (count($host_port) > 1) {
            $seeds[$i]["port"] = $host_port[1];
        }
    }

    for ($i = 0; $i < count($seeds); $i++) {
        $MONGO["servers"][$i]["mongo_name"] = $seeds[$i]["name"];//mongo server name
        //$MONGO["servers"][$i]["mongo_sock"] = "/var/run/mongo.sock";//mongo socket path (instead of host and port)
        $MONGO["servers"][$i]["mongo_host"] = $seeds[$i]["host"];//mongo host
        $MONGO["servers"][$i]["mongo_port"] = $seeds[$i]["port"];//mongo port
        $MONGO["servers"][$i]["mongo_timeout"] = 0;//mongo connection timeout
        //$MONGO["servers"][$i]["mongo_db"] = "MONGO_DATABASE";//default mongo db to connect, works only if mongo_auth=false
        if (getenv("MONGO_AUTH") === 'true') {
            $MONGO["servers"][$i]["mongo_auth"] = true; //enable mongo authentication?
            $MONGO["servers"][$i]["control_auth"] = false; //enable control users, works only if mongo_auth=false
        } else {
            $MONGO["servers"][$i]["mongo_auth"] = false; //enable mongo authentication?
            $MONGO["servers"][$i]["control_auth"] = true; //enable control users, works only if mongo_auth=false
            {{- if .Values.rockmongo.controlUsers.enabled }}
              {{- if .Values.rockmongo.controlUsers.list }}
                {{- range $user := .Values.rockmongo.controlUsers.list }}
            $MONGO["servers"][$i]["control_users"]["{{ $user.name }}"] = "{{ $user.password }}";
                {{- end }}
              {{- else }}
            $MONGO["servers"][$i]["control_users"]["admin"] = "admin";
              {{- end }}
            {{- end }}
        }
        $MONGO["servers"][$i]["ui_only_dbs"] = ""; //databases to display
        $MONGO["servers"][$i]["ui_hide_dbs"] = ""; //databases to hide
        $MONGO["servers"][$i]["ui_hide_collections"] = ""; //collections to hide
        $MONGO["servers"][$i]["ui_hide_system_collections"] = getenv("MONGO_HIDE_SYSTEM_COLLECTIONS") === "true"? true: false; //whether hide the system collections
    }
    ?>
{{- end }}
