apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
data:
  mongod.conf: |-
    storage:
      dbPath: /data/db
    net:
      port: {{ .Values.port }}
    replication:
      replSetName: {{ .Values.replicaSet }}
    {{- if .Values.auth.enabled }}
    security:
      authorization: enabled
      keyFile: /keydir/key.txt
    {{- end }}
