# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  {{- if .Values.serviceAnnotations }}
{{ toYaml .Values.serviceAnnotations | indent 4 }}
  {{- end }}
  labels:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: peer
      port: {{ .Values.port }}
  selector:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
