{{- if .Values.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-certs
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
type: Opaque
data:
  tls.crt: {{ .Values.ssl.cert }}
  tls.key: {{ .Values.ssl.key }}
{{- end }}
