apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.metrics.port }}
    {{- end }}
  labels:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.service.loadBalancer }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
  selector:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
    {{- if .Values.ssl.enabled }}
    - name: https
      port: {{ .Values.ssl.port }}
      targetPort: {{ .Values.ssl.port }}
    {{- end }}
