{{- if .Values.pgadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-pgadmin
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  {{- if .Values.pgadmin.service.loadBalancer }}
  type: LoadBalancer
  {{- else }}
  type: ClusterIP
  {{- end }}
  selector:
    application: {{ template "fullname" . }}
    component: pgadmin
  ports:
    - name: pgadmin
      port: {{ .Values.pgadmin.port }}
      targetPort: {{ .Values.pgadmin.port }}
{{- end }}
