apiVersion: v1
kind: Endpoints
metadata:
  name: {{ template "fullname" . }}-conn
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
    supervisor: patroni
subsets: []
