apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
    {{- end }}
  name: {{ template "fullname" . }}-conn
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
    supervisor: patroni
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
