apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-creds
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
type: Opaque
data:
  password-superuser: {{ .Values.credentials.superuser | b64enc | quote }}
  password-admin: {{ .Values.credentials.admin | b64enc | quote }}
  password-standby: {{ .Values.credentials.standby | b64enc | quote }}
