{{- if .Values.pgadmin.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-pgadmin-creds
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: pgadmin
    supervisor: patroni
type: Opaque
data:
  user: {{ .Values.pgadmin.credentials.user | b64enc | quote }}
  password: {{ .Values.pgadmin.credentials.password | b64enc | quote }}
{{- end }}
