apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-conn
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
    supervisor: patroni
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
