clusterName: rabbitmq0
replicas: 3

service:
  loadBalancer: false
  # Annotations to be added to the service
  annotations: {}
  ingress:
    enabled: false
    annotations: {}
    hosts: []
    tls: []

# management port is mgmtPort if no SSL, mgmtPort-1 otherwise
config:
  nodePort: 5672
  mgmtPort: 15672
  nodeName: rabbitmq
  erlangCookie: 7lOiTR8Zxs2rsTVx
  defaultVhost: "/"
  ssl:
    enabled: false
  auth:
    enabled: false
    defaulUser: guest
    defaultPass: guest

# Specs for the Docker image for the init container that establishes the cluster
installImage:
  name: tadaweb/rabbitmq-install
  tag: 0.1
  pullPolicy: Always

# Specs for the MongoDB image
# use the following if you want to have the exporter enabled in rabbitmq
# directly
# image:
#   name: deadtrickster/rabbitmq_prometheus
#   tag: 3.6.10
image:
  name: rabbitmq
  tag: 3.6.10-management
  pullPolicy: IfNotPresent

# Annotations to be added to MongoDB pods
podAnnotations: {}

resources:
  requests:
    cpu: 100m
    memory: 512Mi
# limits:
#   cpu: 100m
#   memory: 512Mi

persistentVolume:
  enabled: true
  storageClass: default
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations: {}

metrics:
  enabled: false
  port: 9090
  # use a different user and password than the default.
  # the user must exist
  # rabbitmqUser:
  # rabbitmqPassword:

  image:
    name: kbudde/rabbitmq-exporter
    tag: v0.20.0
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

  # Regexp matching queues names respectively are not exported and are exported
  # skipQueues: ".*"
  # includeQueues: "^$"
