replicaSet: rs0
replicas: 3
port: 27017

auth:
  enabled: false
  # adminUser:
  # adminPassword:
  # key:
  # existingKeySecret:
  # existingAdminSecret:

# Specs for the Docker image for the init container that establishes the replica set
installImage:
  name: gcr.io/google_containers/mongodb-install
  tag: 0.4
  pullPolicy: IfNotPresent

# Specs for the MongoDB image
image:
  name: mongo
  tag: 3.4
  pullPolicy: IfNotPresent

# Annotations to be added to MongoDB pods
podAnnotations: {}

resources:
  requests:
    cpu: 100m
    memory: 512Mi
# limits:
#   cpu: 100m
#   memory: 512Mi

persistentVolume:
  enabled: true
  storageClass: default
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  annotations: {}

# Annotations to be added to the service
serviceAnnotations: {}

rockmongo:
  enabled: false
  port: 8085
  image:
    name: tadaweb/rockmongo
    tag: 1.1.7
    pullPolicy: IfNotPresent
  hideSystemCollections: false
  service:
    loadBalancer: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  controlUsers:
    enabled: false
    # This option is deprecated!
    # if controlUsers enabled use the list to define them
    # list:
    #   - name:
    #     password:

mongoexpress:
  enabled: false
  port: 8081
  image:
    name: mongo-express
    tag: 0.40.0
    pullPolicy: IfNotPresent
  service:
    loadBalancer: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  gridfsEnabled: true
  requestSize: 1mb
  editorTheme: lesser-dark
  # Used only when mongodb.auth is disabled
  controlUser:
    name: admin
    password: admin


metrics:
  enabled: false
  port: 9216

  image:
    # to be replaced with the exporter by Percona
    # this supports the authentication but must be passed as a cli argument.
    # The cli cannot be used with env variables because the container does not have a shell.
    name: crobox/mongodb-exporter
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
