replicas: 1
port: 80

image:
  name: traefik
  tag: 1.3.1
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  # limits:
  #   cpu: 100m
  #   memory: 100Mi

rbac:
  enabled: false

service:
  loadBalancer: true
  annotations: {}

terminationGracePeriodSeconds: 10

nodeSelector: {}
  #key: value
tolerations: []
# E.g. kubernetes   ---  https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
# - key: "key1"
#   operator: "Equal"
#   value: "value1"
#   effect: "NoSchedule"
# - key: "key1"
#   operator: "Equal"
#   value: "value1"
#   effect: "NoExecute"
ssl:
  enabled: false
  enforced: false
  port: 443
  cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnekNDQW11Z0F3SUJBZ0lKQUxtbkVhSnVXM1BXTUEwR0NTcUdTSWIzRFFFQkN3VUFNRmd4Q3pBSkJnTlYKQkFZVEFreFZNUk13RVFZRFZRUUhEQXBNZFhobGJXSnZkWEpuTVJVd0V3WURWUVFLREF4VVlXUmhkMlZpSUZNdQpRUzR4SFRBYkJnTlZCQU1NRkdWNFlXMXdiR1V1ZEhKaFpXWnBheTVwYm1adk1CNFhEVEUzTURjeE56RTBORGMwCk1Gb1hEVEkzTURjeE5URTBORGMwTUZvd1dERUxNQWtHQTFVRUJoTUNURlV4RXpBUkJnTlZCQWNNQ2t4MWVHVnQKWW05MWNtY3hGVEFUQmdOVkJBb01ERlJoWkdGM1pXSWdVeTVCTGpFZE1Cc0dBMVVFQXd3VVpYaGhiWEJzWlM1MApjbUZsWm1sckxtbHVabTh3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzlMZDZ4CnkrUXpNM1ZGQlFvdjExNnlJL3VoZzlMckV4VVlJZWlTdjJVMjlsQmRheStReXhuWHpNby81RmpYVGlVUGowYjEKNlpVK2JJMXR3dnJnRzVqazl6RjBSQmxNZFM3RWI5Zm5CNjh6dnRxMWNjd01yM2NIVzZBc0ROeEpTSlVuZ3FqYwp6STFvME15RlhhdytmdlZIMzB4b2x1c1Yrd2p5MWwxcHJINFptTWFKLzVsSDB5cEpoVTRxeS9GRTBja3B6R003Ck9sQklyRnI2dW8zbFluVGFpWTJFZnlYdjR5SGVqZFd6Vm9ZSFl3d3Y3SFMxNGxXaWJsSWM5Ukxybk81MS9iNHgKR3FqODRUakJlc0F3RkNFNkJZUTB5dHU1REZMTnZBOFIvNC9qWTNnOXhqc1krclpGdC91TFVZKzlMQ3daR05wYwpwTktZZzhJb3g0R2JrRXhUQWdNQkFBR2pVREJPTUIwR0ExVWREZ1FXQkJTcExxS21LSmdnbTBzZCs2NUtkTmwyCmhhWEVZekFmQmdOVkhTTUVHREFXZ0JTcExxS21LSmdnbTBzZCs2NUtkTmwyaGFYRVl6QU1CZ05WSFJNRUJUQUQKQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0RzLzBJVkUzekdEcGdPRDdmdWI3OXRRZkJJT0hkOXhTYwpPdCtWMi9hQU9WU3ZYc2E3OEtpQVRkSHhQWFIrZVRKWENDcGkzR3BqQTdtRUovTkZ2Q3RnZlFtNURtMlM4eTBxCnh6a3pQT3VuT292ZjR2SmpHdXc3cVhmRWsrdXgrUWhNc2YvRVNueFhvWDNBK0ZFSWlwYisvUy9Pd0ZlYXNxc0wKc1NHY1pPSnFCYk9RdUpDQk9EOUt4TkdONXNPVFN4VWxlRm9BVEkxZlNjSllwQ1NHb2Q0c2tZNFBFalh3R3cvcAprMEE0Q0RIMks4YktiUHA4NWtxSHVWVHBOTFZ0SFcwczcya0ZTRmpwQ05lUWJ5VmJ4QTNpcExBRTVWdzNyZUJ2CmVmUmRjTlRWcjFSdElvQ0NmdytIUUlUTThNSmYzSzJHUlpMSTdjaXREeU1tWjkyRVZwczgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQzlMZDZ4eStRek0zVkYKQlFvdjExNnlJL3VoZzlMckV4VVlJZWlTdjJVMjlsQmRheStReXhuWHpNby81RmpYVGlVUGowYjE2WlUrYkkxdAp3dnJnRzVqazl6RjBSQmxNZFM3RWI5Zm5CNjh6dnRxMWNjd01yM2NIVzZBc0ROeEpTSlVuZ3FqY3pJMW8wTXlGClhhdytmdlZIMzB4b2x1c1Yrd2p5MWwxcHJINFptTWFKLzVsSDB5cEpoVTRxeS9GRTBja3B6R003T2xCSXJGcjYKdW8zbFluVGFpWTJFZnlYdjR5SGVqZFd6Vm9ZSFl3d3Y3SFMxNGxXaWJsSWM5Ukxybk81MS9iNHhHcWo4NFRqQgplc0F3RkNFNkJZUTB5dHU1REZMTnZBOFIvNC9qWTNnOXhqc1krclpGdC91TFVZKzlMQ3daR05wY3BOS1lnOElvCng0R2JrRXhUQWdNQkFBRUNnZ0VBSjcrZGpPbjBOclhYSy90Vkdwdzc3MTRVSHVtZHhYcXE4ZmtkN3NkOE1zSXEKUEphcTFkZDJ4SnJvMitmVXF0aG1mUkJ6cm5PM3dmZjQ5MWtDY1ZnYkZmRENXVlY5bzB6ejJKNVBWT0dPZEdiagplVUJCeVdDTXQrVU9rSExiVGlLTUJGTTF1NzdXNzNEL3AvMzRsT0VFRkdmY25CVXBxK0tsRExEeHk2Uk1rbi9rCmd3aGh4cW5lbTl6a0J4SFArLzZrK05neVIvT2RzVDk0UE14czNWdm9OajlHSVBjNWMvODJSZTczS0VmYVlMclcKREtSWFJEMjd2N2FScFI1L1I0SERxZUtrd3prNnI0d0g4djZnWWZzd0tjTDBuR1pWM3d6S0ZWUWdSSVlaUXhwdQpJNWVtOHM0MzZFeDY0aC9nMVo5RVhPbnhkWTdMUTRTYUl5UGlpWENLY1FLQmdRRHBpc0dpMXZYYTM4UVBiazMvCmdqemwrbmJZWklrQXFLNVc5QWgrRDZvTTdsdUNTMzNrWVNjOEgveHZRVDZSTTEwRzFMTEFvZFhaOC9OOXJxYk0KT25WSUFaU0xZaW5yWGxyazJWTDFtU1Q4bU9Uck1mTDlsZkM4bjZrQ3plMzkvZEh3anJmSERnbllUZ2pPRWhMQQpMUHdka3EwK1lLaU4rM1BFUDdKeWduWXZoUUtCZ1FEUFh3SEpaTWx1WkJORmJncFROK3JNTnp0MDVmbjR5Y3o3Clc1SUVXWHJnazRKNlVhR3dtU3Q1K0FkYitXc1ZiUjRadmUvbDkxTlF5Sk5yVW9jb1dlZmw1T3MyZmV1Y2ViTncKY1p1Tkp6V1p6MitIWEl2bU41VTUycXV3VFZINVBidSsrVE9wcHF6L0ExQ3M3Rmo0STIxN2JibkNjS2loT3BHdwpwb2FMbU0yWDl3S0JnR05IalZHQU9EdTNiRTF6QXMxZnZDdTM4ZFhEeDBuMGEwaWpyUWlKK0N4UEY2K29EL2lLCkpIZTIwVVVxWTBLdXB4bEVTa2tCZ3p1SUxUWjhqSU85UmlZNkpiK3JGMDdyYVpCbm9wQ3RiYi9ENzJ6Y2F3UEsKUGZDeG50T0dYMm5lQU9WV2htR2tZaU1GNlZCUTlvK2pqL215Wk50ams4UG41U3JFT1VQY21nbFJBb0dCQUthQgpkSi9PeTJaVitKdFJCZjFYOHJIU3oyekhrL1ZObzhkWCtXQ0FzSWRPS2dBcE41ampBK1BGWWJOYUM3K0NoQjdMClFhcjI4ZkQxZkZrNlJNZ0RtSTRoUnpQVDI3RWlqeEFFU0pBSUlhUEV5WnA0bHVSZFVQYkpPLzR0dDFwWFZUNjgKUGQxRXRiZDFZL3ZWTW9MYmYzY1IzWXZnaGFZZnJ3ZVdUb1ljUlVoMUFvR0FWcjdwUHBwZWtwaGVKRWVhZWRDQgpSOVVhODJ6Tlg1YXp0a2VZbHYxclU5YTFKTTRrMzFVWG5sU0Jqam9kOG9vT1poRzh1VFkwaEs1VFFjK3lsYklDCm5SOFBXUFhzeWU5OWY1VVlUNk9HYmNrQUFWZ2ZuWmQvWU9YQ2doZUZGK2ZzZWZqUEN2eGpXY1N5aU5nMXhVZncKSWplc0dINnZvbHRJTXRUa2EwMngyZm89Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K

metrics:
  enabled: false
  public: false
  port: 8080
  auth: {}
  # dictionary of users and passwords
  #   user1: password1
  #   user2: password2

config:
  # namespaces to watch. "default" and "production" are enabled by default
  namespaces:
    - "default"
    - "production"
  acme:
    enabled: false
    email: admin@example.com
    staging: true
    # Save ACME certs to a persistent volume. WARNING: If you do not do this, you will re-request
    # certs every time a pod (re-)starts and you WILL be rate limited!
    persistentVolume:
      enabled: true
      storageClass: default
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      annotations: {}
  gzip:
    enabled: true
