apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: "{{ template "fullname" . }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.ports.peer }}
    name: etcd-peer
  - port: {{ .Values.ports.client }}
    name: etcd-client
  selector:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
