{{- if .Values.config.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}-creds
type: Opaque
data:
  user: {{ .Values.config.auth.defaultUser | b64enc }}
  password: {{ .Values.config.auth.defaultPass | b64enc }}
{{- end -}}
