apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-amqp
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
    {{- end }}
  labels:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: amqp
      protocol: TCP
      port: {{ .Values.config.nodePort }}
      targetPort: {{ .Values.config.nodePort }}
  selector:
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
